<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Account registration at {APP_NAME}' => 'Реєстрація облікового запису в {APP_NAME}',
    'Check your email for further instructions.' => 'Перевірте свою електронну пошту, щоб отримати подальші інструкції.',
    'Created at' => 'Створено',
    'E-mail' => 'Електронна пошта',
    'Follow the link below to reset your password {LINK}' => 'Перейдіть за посиланням нижче, щоб змінити пароль {LINK}',
    'Follow the link below to verify your email: {LINK}' => 'Перейдіть за посиланням нижче, щоб підтвердити свою електронну адресу: {LINK}',
    'Hello {USER_NAME},' => 'Привіт, {USER_NAME}!',
    'If you forgot your password you can {ACTION_LINK}.' => 'Якщо ви забули свій пароль, ви можете {ACTION_LINK}.',
    'Incorrect email or password.' => 'Неправильна адреса електронної пошти або пароль.',
    'Login' => 'Вхід',
    'Name' => 'Ім\'я',
    'Need new verification email? {ACTION_LINK}' => 'Потрібен новий лист для підтвердження? {ACTION_LINK}',
    'New password saved.' => 'Новий пароль збережено.',
    'Password' => 'Пароль',
    'Password reset for {APP_NAME}' => 'Скидання пароля для {APP_NAME}',
    'Password reset token cannot be blank.' => 'Токен скидання пароля не може бути пустим.',
    'Please choose your new password:' => 'Вкажіть свій новий пароль:',
    'Please fill out the following fields to login:' => 'Будь ласка, заповніть наступні поля для входу:',
    'Please fill out the following fields to signup:' => 'Будь ласка, заповніть наступні поля для реєстрації:',
    'Please fill out your email. A link to reset password will be sent there.' => 'Будь ласка, заповніть свою електронну адресу. На неї буде надіслано посилання для скидання пароля.',
    'Please fill out your email. A verification email will be sent there.' => 'Будь ласка, заповніть свою електронну адресу. На неї буде надіслано лист для її підтвердження.',
    'Remember me' => 'Запам\'ятати мене',
    'Request password reset' => 'Запит на скидання пароля',
    'Resend' => 'Надіслати повторно',
    'Resend verification email' => 'Повторно надіслати електронний лист для підтвердження',
    'Reset password' => 'Скинути пароль',
    'Save' => 'Зберегти',
    'Send' => 'Надіслати',
    'Signup' => 'Реєстрація',
    'Sorry, we are unable to resend verification email for the provided email address.' => 'На жаль, ми не можемо повторно надіслати електронний лист із підтвердженням для вказаної електронної адреси.',
    'Sorry, we are unable to reset password for the provided email address.' => 'На жаль, ми не можемо скинути пароль для наданої електронної адреси.',
    'Sorry, we are unable to verify your account with provided token.' => 'На жаль, ми не можемо підтвердити ваш обліковий запис за допомогою наданого токена.',
    'Status' => 'Статус',
    'Surname' => 'Прізвище',
    'Thank you for registration. Please check your inbox for verification email.' => 'Дякуємо за реєстрацію. Будь ласка, перевірте свою поштову скриньку на наявність електронного листа для підтвердження.',
    'There is no user with this email address.' => 'Користувачі із цією електронною адресою відсутні.',
    'This email address has already been taken.' => 'Ця електронна адреса вже зайнята.',
    'Updated at' => 'Оновлено',
    'Verify email token cannot be blank.' => 'Токен перевірки електронної пошти не може бути пустим.',
    'Wrong password reset token.' => 'Неправильний токен скидання пароля.',
    'Wrong verify email token.' => 'Неправильний токен підтвердження електронної пошти.',
    'Your email has been confirmed!' => 'Вашу адресу електронної пошти підтверджено!',
    'reset it' => 'скиньте його',
    '{NAME} {SURNAME}' => '{NAME} {SURNAME}',
];
