<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Active' => 'Активна',
    'Add new purchase' => 'Додати нову закупку',
    'Budget' => 'Бюджет',
    'Create purchase' => 'Додати закупку',
    'Created At' => 'Створено',
    'Created By' => 'Створив',
    'Description' => 'Опис',
    'Draft' => 'Чернетка',
    'Error during purchase creation.' => 'Помилка під час створення закупки.',
    'Error during purchase update.' => 'Помилка під час оновлення закупки.',
    'ID' => 'ID',
    'My purchases' => 'Мої закупки',
    'Name' => 'Назва',
    'Nomenclature' => 'Номенклатура',
    'Purchase' => 'Закупка',
    'Purchase nomenclatures must contains at least 1 item.' => 'Закупівельна номенклатура повинна містити не менше 1 позиції.',
    'Purchase successfully created.' => 'Закупку успішно створено.',
    'Purchase successfully updated.' => 'Закупку успішно оновлено.',
    'Purchases' => 'Закупки',
    'Quantity' => 'Кількість',
    'Save' => 'Зберегти',
    'Select status' => 'Вкажіть статус',
    'Status' => 'Статус',
    'Status can\'t be set to "{STATUS_NAME}".' => 'Не можна встановити статус "Чернетка"',
    'The requested purchase does not exist.' => 'Закупка не існує.',
    'Units' => 'Одиниці виміру',
    'Update' => 'Оновити',
    'Update purchase: {NAME}' => 'Редагування закупки: {NAME}',
    'Updated At' => 'Оновлено',
    'Updated By' => 'Оновив',
];
